sudo: required
dist: trusty

language: cpp

os:
  - linux
  
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9


before_script:
  - ./scripts/fetch_folly_ubuntu_trusty.sh
  - ./scripts/prepare_ubuntu_trusty.sh
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=DEBUG ..
  - make -j8
  - ./tests
